name: smoothapp_poc
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'
dependencies:
  flutter:
    sdk: flutter

  provider: any
  flutter_svg: any
  bottom_sheet: any
  mobile_scanner: any
  visibility_detector: any

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.svg
    - assets/images/barcode.svg

  fonts:
    - family: DroidSans
      fonts:
        - asset: assets/fonts/DroidSans.ttf
        - asset: assets/fonts/DroidSans-Bold.ttf
          weight: 700